apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  targetNamespace: vault
  chart:
    spec:
      chart: vault
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 15
  values:
    global:
      enabled: false
      tlsDisable: true
    injector:
      enabled: true
      logLevel: "debug"
    ui:
      enabled: true
      serviceType: ClusterIP
    server:
      enabled: true
      logLevel: "debug"
      standalone:
        enabled: false
      dataStorage:
        enabled: true
        size: 6Gi
        mountPath: "/vault/data"
        storageClass: "hostpath"
        accessMode: ReadWriteOnce
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }